prgrms-web-devcourse-final-project/WEB1_1_Bongdari_FE

- src/components/label/AidRqCategoryLabel/index.tsx
- src/components/label/AidRqCategoryLabel/indexCss.ts
- src/components/label/AidRqCertifiedLabel/index.tsx
- src/components/label/AidRqCertifiedLabel/indexCss.ts
- src/components/label/AidRqStateLabel/index.tsx
- src/components/label/AidRqStateLabel/indexCss.ts
- src/components/label/MessageLabel/index.tsx
- src/components/label/MessageLabel/indexCss.ts
- label컴포넌트를 개발했습니다.
- 재사용성을 위하여 개발했고, 가져다가 쓰시면 됩니다.
- 사용방법
- AidRqCategoryLabel 의 경우 모집유형 명을 string으로 text라는 이름의 props로 넘겨주면 됩니다.
- AidRqCertifiedLabel의 경우 props는 따로 없고, 시간인증이 된 요청글에서만 넣으면 됩니다.
- AidRqStateLabel의 경우 모집상태를 '모집중' / '모집완료' / '종료' 셋중 하나의 string 값으로
state라는 이름의 props로 넘겨주면 됩니다. (띄어쓰기X)
- MessageLabel의 경우 props는 따로 없고, 읽음처리가 아직 안된 쪽지아이템에서만 넣으면 됩니다.
<br/>
<br/>
- 수정할 부분이 있으면 수정
- Issue: #
- 이해가 잘 안되거나 사용이 불편한 부분이 있으면 언제든 편하게 말씀해주세요.
> ✨[#22] Feat: label component 개발완료

- index.html
- src/components/modal/index.tsx
- src/components/modal/indexCss.ts
- src/components/modal/logic/useModal.ts
- src/styles/theme.ts
- components 폴더에 modal 폴더 생성
- logic 폴더에 모달 open, close 함수를 useModal 훅으로 만듦 -> 불러올 때 아래와 같이 불러와서 쓰면 됨
```
const { isModalOpen, openModal, closeModal } = useModal();
```
- theme.ts에 있는 내용에 따라 variant를 big, small로 나누어 width, height 지정
<br/>
<br/>
- Issue: #27
> ✨ [#27] Feat: 모달 컴포넌트 구현

- src/components/textArea/index.tsx
- src/components/textArea/indexCss.ts
- src/components/textArea/logic/useInput.ts
> src/component/textArea/index.tsx
> src/component/textArea/indexCss.ts
> src/component/textArea/logic/useinput.ts
- inputBox와 거의 동일합니다.
- 여러 줄 입력이 가능하고 Enter키 event 삭제했습니다.
<br/>
- inputBox와 거의 동일합니다
<br/>
- 사용하면서 수정사항 필요시 고칠 생각
- Issue: #15
> ✨ [#15] Feat: textArea 구현(inputBox와 기능 동일)

- src/components/modal/index.tsx
- src/components/modal/indexCss.ts
- src/shared/hooks/useScrollLock.tsx
공용 훅으로 분리해서 사용했습니다.
`getScrollbarWidth`  함수로 스크롤바 너비를 계산하고 `useScrollLock` 훅 함수를 만들어 안에 
`useCallback` 을 사용해 현재 body에 적용된 속성들을 기억하는 `originalStyle`을 객체로 만들어 저장하고, 모달을 열었을 때 적용될 속성들을 getScrollbarWidth를 사용해 만들어주었고,
그리고 cleanup 함수를 통해 모달을 닫았을 때 이전에 저장된 원래 스타일대로 복원하는 작업도 해주었습니다. 
자세한 내용은 코드마다 주석으로 달아두었으니 확인해보시면 될 것 같습니다. 
<br/>
<br/>
- Issue: #82
> ♻️ [#82] Refactor: 모달 컴포넌트 z-index 높이기, isOpen시 브라우저 이벤트 막기

- src/components/inputBox/index.tsx
- src/components/search-bar/filter-search/index.tsx
- src/components/search-bar/nonfilter-search/index.tsx
- src/features/applicant-detail-modal/index.tsx
- src/features/applicant-detail-modal/indexCss.ts
- src/pages/aidrq-list-page/ui/aidrqlist-wrapper/index.tsx
flex -> grid로 변경
- grid로 만들 div(타이틀~등급 / 프로필 이미지 / 설명)을 3개로 나누고, 설명을 담당하는 div가 해당 행의 모든 열을 차지하도록 하여 모달 너비를 전부 차지하도록 변경하였습니다. 
<br/>
<br/>
- Issue: #92
> ♻️ [#92] Refactor: 모달 레이아웃 변경

- package.json
- src/components/alert-item/index.tsx
- src/components/alert-item/indexCss.ts
- src/features/alert/index.tsx
- src/features/alert/logic/single-read/index.ts
- src/layout/header/Header.tsx
- yarn.lock
- sse연결 후, 알림이 오는대로 토스트버튼 띄우기 (일단 되는지 확인하고, css만질 예정)
- 종아이콘 클릭 시, 읽지않은 모든 알림들 get해오기
- 삭제버튼 클릭 시, console에 해당 알림 id 띄우도록 처리해놓음. (api개발되면 연결하면 됨)
<br/>
<br/>
- Issue: #
> ✨feat : 알림 토스트 및 알림전체조회 및 읽기기능 구현

- src/components/inputBox/index.tsx
- src/components/inputBox/logic/useInput.ts
- src/components/long-list-item/index.tsx
- src/components/long-list-item/indexCss.ts
- src/components/long-list-item/ui/CommunityInfo.tsx
- src/components/long-list-item/ui/CommunityInfoCss.ts
- src/components/search-bar/nonfilter-search/index.tsx
- src/features/community-list/index.tsx
- src/features/community-list/indexCss.ts
- src/features/community-list/logic/fetchCommunityList.ts
- src/features/community-list/logic/useCommunityList.ts
- src/pages/community-list-page/index.tsx
- src/pages/main-page/_components/community/index.tsx
- src/pages/main-page/_components/community/indexCss.ts
- src/shared/types/community-type/CommuntiyTypes.ts
- main에서 더보기 클릭시 community list page로 이동
- Enter / 검색 버튼 클릭시 검색 데이터 fetch
- 페이지당 10개씩 가져오기, pagenation 기능 구현
- 요소 클릭시 community detail page로 이동
- 작성하기 버튼 => 개인으로 로그인시 활성화
<br/>
<br/>
- Issue: #162
> ✨ [#162] community list page api 연결 및 주변 코드 수정

- src/components/aidrq-create-location/useKakaoLoader.tsx
- src/features/aidreq-detail-admin-info/_components/activity-location/index.tsx
- src/features/aidreq-detail-info/_components/location/index.tsx
- src/features/find-nearby-activity-search/index.tsx
- src/pages/find-nearby-activitiy-page/index.tsx
- src/shared/hooks/useGoToKakaoMap.ts
- 카카오맵 api key env 파일에 있는 환경 변수로 사용 변경
- 지도보기 클릭 -> 카카오맵 지도 길찾기 로직 훅으로 분리
- 봉사자 모집글 상세 페이지 지도 보기 버튼 클릭 시 길찾기 이동 훅 사용
<br/>
<br/>
- Issue: #182
> ✨ [#182] Feat: 지도 페이지 훅 분리

- src/features/aidreq-detail-admin-recruit-state/index.tsx
- src/store/queries/aidreq-detail-center/useRecruitBoard.ts
- 백엔드에서 patch 요청에 대해 cors 설정을 추가해주었고,
- 요청 헤더에 토큰을 넣어주지 않아 통신이 안되어 직접 헤더에 Cookie.get('centerToken')을 넣어주었습니다.
- 로그인 구현이 완료되고 토큰이름이 바뀐다면 변경해주어야 합니다.
<br/>
<br/>
- Issue: #184
> 🐛 [#184] Fix: 모집 상태 요청 header에 토큰 추가

- src/features/aidreq-detail-admin-recruit-state/index.tsx
- src/pages/aidrq-detail-admin-page/index.tsx
- src/pages/aidrq-detail-admin-page/ui/button-group/index.tsx
- 모집 상태가 성공적으로 변환되었으면 alert창으로 "모집 상태가 성공적으로 변경 되었습니다." 띄워주었습니다. (임시로 처리해놓은 것이고, 후에 토스트나 팝업창으로 띄워주면 좋을 것 같습니다.)
- status를 props로 넘겨서 status !== 'COMPLETED' (종료)일 때 "정산하기 버튼을 disabled 처리 해놓았습니다.
<br/>
<br/>
- Issue: #186
> 🐛 [#186] Fix: status !== 'COMPLETED'일 때 "정산하기"버튼 disabled 처리

- src/components/applicant-list-item/index.tsx
- src/pages/aidrq-create-page/index.tsx
- src/pages/aidrq-detail-page/index.tsx
- src/pages/aidrq-modify-page/ui/info-modify/index.tsx
- src/pages/aidrq-modify-page/ui/info-modify/indexCss.ts
- src/pages/aidrq-modify-page/ui/location-modify/index.tsx
- src/pages/aidrq-modify-page/ui/location-modify/indexCss.ts
- 활동 지원하기, 활동글 수정하기, 활동글 등록하기에 dialog추가
- '등록 후 새로고침 -> 등록 후 api만 재호출' 로 변경
<br/>
<br/>
- Issue: #
> ✨feat: 작성 수정 지원 등에 dialog추가

- src/pages/main-page/MainPage.tsx
- src/store/stores/interest-center/interestStore.ts
- 메인페이지에서 관심기관 불러와서 저장
- local과 연동
<br/>
<br/>
- detail페이지 들어갈때 관심기관 여부 판별하기
- interest heart 클릭 시에 zustand와 연동시키기
- Issue: #
> ✨feat:main에서 관심기관 리스트 불러와서 저장

- src/api/routes/index.tsx
- "/*" 경로였던 에러 페이지를 "/error"로 변경
- Issue: #347
> ♻️ [#347] Fix: 에러 페이지 라우팅 주소 "/error"로 변경

- src/features/register-goods/index.tsx
- src/features/register-goods/logic/useAddItem.ts
- src/pages/center-my-page/index.tsx
- src/store/queries/center-mypage/usePreferItems.ts
- 물품 등록 쿼리 키는 preferItem, 프로필 조회할 때 쓰이는 쿼리키는 centerProfile이었는데, 
물품등록 응답은 centerProfile에 포함되기 때문에 물품 등록 post, delete 요청의 쿼리키도 preferItem -> centerProfile로 맞춤
- react query의 invalidateQueries로 캐시 무효화를 하기 위해서는 useState로 로컬 즉시 반영되는 부분을 지워야 했음
<br/>
- Issue: #370
> 🐛 [#370] Fix: 물품등록 ui 즉시 반영되도록 수정

- src/features/applicant-detail-modal/index.tsx
- src/features/applicant-detail-modal/indexCss.ts
- 기관이 조회할 수 있는 봉사활동 지원자 현황 페이지의 단건 조회 모달에서, 
지원자 상세 프로필 get 요청에서 이메일 필드 삭제
- Issue: #390
> 🐛 [#390] Fix: 지원자현황 단건 조회에서 지원자 이메일 필드 삭제

- src/features/aidrq-list-regular/indexCss.ts
- 왼쪽으로 치우쳐져 있길래 aidList Wrapper에 margin: auto 추가했습니다.
<br/>
<br/>
- Issue: #397
> ♻️ [#397] Refactor: 활동구인 페이지 도움요청글 리스트 Wrapper에 margin: auto 설정

- src/components/modal/indexCss.ts
- max-width: 1000px 일 때 width: 90%로 변경
- close-button을 max-width: 1000일 때, top: 4px right: 4px로 변경
<br/>
<br/>
- Issue: #419
이제 쪽지/리뷰 모달 반응형 작업 시작하시면 됩니다!
> ✨ [#419] Feat: 모달 반응형 적용

- src/pages/aidrq-detail-page/ui/title/index.tsx
- 모집글 상태를 보여주는 라벨이 항상 '모집중'으로 되어있던 것 수정.
<br/>
<br/>
- Issue: #
> 🐛fix:모집글 상태라벨 조건처리

- src/features/message-create-modal/logic/useSendMail.ts
- src/layout/Layout.tsx
- src/layout/LayoutCss.ts
- src/layout/header/Header.tsx
- src/pages/aidrq-create-page/logic/validateVolunteerData.ts
- src/pages/aidrq-modify-page/logic/validateVolunteerData.ts
- 모집글작성/수정/쪽지작성에 글자수제한 유효성검사 추가
- 로그아웃 시 오류부분 개선 (set함수와 api함수의 순서가 맞지않아서 오류가 발생)
- Layout.tsx에서 나는 오류개선 (Wrapper컴포넌트의 스타일컴포넌트를 body로 줘서 났던 오류)
- Footer하단에 붙어있지 않는 오류개선 (flex:1 미스)
<br/>
<br/>
- 리뷰, 마이페이지, 커뮤니티는 추가적으로 유효성검사 필요
- Issue: #
> 🐛fix:오류개선 및 글자수제한

- src/pages/main-page/MainPage.tsx
사이트를 로그아웃하지 않은 상태로 처음 들어왔을 때, 로그인 되어있는 오류
로그아웃을 누르면 zustand는 사라지지만 로그아웃 api는 오류코드가 발생함
main에 들어왔을 때, token이 없는 경우, 자동으로 logout 시키는 것으로 변경
<br/>
<br/>
- Issue: #
> 🐛fix:사이트재접 시 오류 개선

- src/components/inputBox/index.tsx
- src/components/inputBox/indexCss.ts
- src/components/tinyMCE-editor/index.tsx
- src/features/communitiy-detail-comment-box/index.tsx
- src/features/communitiy-detail-comment-box/ui/CommentInput.tsx
- src/features/communitiy-detail-content-box/index.tsx
- src/features/communitiy-detail-content-box/indexCss.ts
- src/features/community-list/index.tsx
- src/features/community-list/indexCss.ts
- 글자수 제한 적용하기 (1000자) - 텍스트 에디터
- db에서 가져온 html형식의 string을 html로 변환하여 표시하도록 수정
- 커뮤니티 댓글 비활성화
- 커뮤니티 리스트 검색결과 없을 때 글자 띄우기
<br/>
------
<br/>
- Issue: #498
> 498 feature 커뮤니티 수정사항

- src/shared/hooks/useCenterInfiniteAidRq.ts
- /center/me로 돼있던 부분은 /me로 변경하였습니다. 
- 스웨거 테스트 시에 인증이 안되었다는 400 에러가 발생하여 헤더에 토큰을 추가하여 했는데, 
axiosInstance로 변경하며 자동으로 헤더에 토큰이 요청에 포함되기 때문에 axiosInstance로만 바꾸어 에러를 해결할 수 있었습니다.
<br/>
- Issue: #535
> 🐛 [#535] Fix: axiosInstance로 바꾸면서 자동으로 헤더에 토큰 추가됨

- src/components/applicant-list-item/index.tsx
- src/shared/types/aidrq-volunteer-list/volunteerListType.ts
- Volunteer 타입에 email 삭제, contact_number: string; 추가
- src/components/applicant-list-item/index.tsx에 email -> contact_number 변경
<br/>
<br/>
- Issue: #547
> ♻️ [#547] Refactor: 지원자 페이지 email 필드 contact_number로 변경

- src/layout/Layout.tsx
- src/pages/detail-info-page/center/index.tsx
- src/pages/detail-info-page/center/indexCss.ts
- src/pages/detail-info-page/center/logic/putCenterInfo.ts
- src/pages/detail-info-page/volunteer/index.tsx
- src/pages/detail-info-page/volunteer/indexCss.ts
- src/pages/detail-info-page/volunteer/logic/putVolunteerInfo.ts
- 상세정보입력페이지를 로그인 로직에 연결
- volunteer/center에 따라서 상세정보가 없을 시에만 상세정보 입력페이지로 이동.
- 상세설명textarea추가
- logout버튼 추가
- 입력 완료 시, 알림을 띄운 뒤 main으로 리다이렉트
- header안보이게
<br/>
<br/>
- url을 수동으로 쳐서 들어가는 작업 방지
- 유효성 검사
- Issue: #
> ✨feat:상세정보페이지 로그인로직에 연결

- src/pages/center-my-page/index.tsx
- src/pages/success-page/index.tsx
- src/store/stores/login/loginStore.ts
- jwt에서 role_id도 디코딩
- 전역 LoginStore과 localStorage에 모두 저장
- center 마이페이지에서 role_id로 가져오도록 수정
<br/>
<br/>
- Issue: #
> ✨feat:RoleId가져오기

- src/api/routes/index.tsx
- src/components/route/ProtectedRoute.tsx
- src/pages/detail-info-page/center/index.tsx
- src/pages/detail-info-page/volunteer/index.tsx
- 상세정보 미입력 시 타 페이지 이동불가 라우팅처리
- 로그아웃 버튼 대신 건너뛰기 버튼 추가
- 상세정보입력 안해도 열람은 가능한 페이지들이 있도록 처리 (ProtectedRoute 특성상 다 막아두면 오히려 코드가 복잡해짐)
- 로그인 안해도 기능이 필요한 페이지들 블럭처리 (이 부분은 회의 후에 수정 가능)
<br/>
<br/>
- Issue: #
> 🐛fix:상세정보입력여부에 따라 라우팅처리

- package.json
- vite.config.ts
- yarn.lock
- [콘솔에 알 수 없는 경고창](https://github.com/vitejs/vite/discussions/14966)이 너무 많이 떠 콘솔이 지저분해져 이 오류 코드가 뜨는 원인을 찾아보니, html을 파싱할 때 썼던 sanitize-html 라이브러리가 원래 node.js 환경을 위해 만들어진 것인데 브라우저 환경에서 쓰려고 시도하다보니 이런 경고가 발생하는 것이라고 합니다.
- 사이트를 이용하는데엔 경고를 제거해도/하지 않아도 문제 없지만 콘솔창이 더 지저분해지는건 왜인지 마음이 불편해지기에..
- path-browserify, url-browserify, source-map, vite-plugin-node-polyfills 을 설치한 다음 vite.config.js 파일에 아래 사진과 같이 alias와 plugins를 추가해주었더니 경고창이 말끔하게 사라졌습니다. 
- yarn install 한번씩 해주세요,
<br/>
<br/>
- Issue: #569
> 📝 [#569] Docs: vite.config.js에 alias 추가

- src/features/review-read-modal/index.tsx
- src/features/review-read-modal/logic/useFindReview.tsx
- src/store/queries/volunteer-profile/useFetchPersonProfile.ts
지금 봉사자 프로필 데이터에 volunteerId 없음
- 기관이 리뷰 모달 조회할 때 작성자 프로필에 volunteerId를 volunteerData에서 가져오고 있는데 현재 api 응답에는 volunteerId로 쓸 수 있는 게 없었습니다. 
- store에서 myRoleId를 가져와 volunteerId로 사용하였습니다. 
- Issue: #585
> 🐛 [#585] Fix: 기관이 조회하는 리뷰 모달에 volunteerId store에서 가져오기

- src/features/aidreq-detail-center-profile/_components/info-container/index.tsx
- src/features/center-profile-prefer-item-box/index.tsx
- 모집글 센터 프로필, 센터 프로필 페이지 itemName -> item_name으로 변경
<br/>
<br/>
- Issue: #592
> 🐛 [#592] Fix: 모집글 센터 프로필, 센터 프로필 페이지 itemName -> item_name으로 변경

- .github/workflows/CICD.yml
- src/components/tinyMCE-editor/index.tsx
- git secrets랑 CICD 파일에 api key 넣어줬습니다.
- editimage 기능은 다른 api key 필요해서 뺐습니다.
- 
<br/>
<br/>
- Issue: #602
> 🐛 Bug: tinymce api key 넣어주기
