prgrms-web-devcourse-final-project/WEB1_1_Bongdari_FE

- .github/CODEOWNERS
- package.json
- src/pages/main-page/MainPage.tsx
- yarn.lock
- pr을 올렸을 떄 자동으로 reviewer가 할당되기 위해서는 CODEOWNERS 앞에 *를 붙여야 한다고 합니다. 
- 그래서 저희 레포지토리 rules에 pr 규칙 세팅 후, 파일을 수정했습니다. 
<br/>
<br/>
- Issue: #5
> 📝 [#5] Docs: CODEOWNERS 파일 수정

- src/styles/theme.ts
- 스타일가이드를 theme에 넣었습니다.
- 작업하실 때, theme을 참고해서 스타일 가이드를 잡으시면 좋을 것 같습니다.
- 주로 중복되는 요소들에 대한 가이드만 제시하였으니, 이외의 부분은 시안을 참고해 주시면 감사하겠습니다.
<br/>
<br/>
- theme에 들어갔으면 하는 부분 추가 작업 가능
- Issue: #16
> ✨[#16] Feat:theme.ts에 스타일가이드 설정

- src/components/select/index.tsx
- src/components/select/indexCss.ts
- select컴포넌트 개발
- 사용방법
- props는 총 4가지
- 1. text (string / placeholder역할)
- 2. width (string / string으로해서 px과 %모두 가능)
- 3. height (string / string으로해서 px과 %모두 가능)
- 4. data (string[] / option의 string리스트를 담은 배열)
<br/>
<br/>
- Issue: #
> ✨[#24]Feat: select컴포넌트 개발완료

- src/components/aidreq-list-Item/index.tsx
- src/components/aidreq-list-Item/indexCss.ts
- src/components/aidreq-list-Item/ui/bottom/index.tsx
- src/components/aidreq-list-Item/ui/bottom/indexCss.ts
- src/components/aidreq-list-Item/ui/top/index.tsx
- src/components/aidreq-list-Item/ui/top/indexCss.ts
- src/pages/main-page/MainPage.tsx
- src/pages/main-page/MainpageCss.ts
- AidReqListItem 컴포넌트 1차 개발 완료
- 일단 텍스트값은 props로 받은 data가 아닌, 일반 텍스트로 채워놓음. (api 호출 후 데이터 작업이 가능해지면 그때 연결할 예정)
<br/>
<br/>
- data연결, 리스트 feature개발
- Issue: #26
> ✨[#26]Feat : AidReqListItem컴포넌트 1차 개발 완료

- src/components/search-bar/filter-search/index.tsx
- src/pages/aidrq-list-page/ui/tab/index.tsx
- src/store/stores/admin-search/searchStore.ts
- 페이지가 aidrqlist일 때에와 그 이외의 페이지 일때 다른 store를 가져오는 로직 처리
<br/>
<br/>
- api연결되면 list에 뿌려주는 것 까지 테스트 해볼 예정
- Issue: #
> ✨feat : 페이지에 따른 검색 전역상태 옵션처리

- src/components/img-drag-box/index.tsx
- src/components/img-drag-box/indexCss.ts
- src/features/review-create-modal/index.tsx
- src/features/review-create-modal/indexCss.ts
- src/features/review-create-modal/logic/handleFileSelect.ts
- src/pages/aidrq-detail-page/index.tsx
- yarn.lock
- 이미지 업로드하는 component개발
- 리뷰 작성 모달 개발
- api연결되면, post연결하면 될듯
<br/>
<br/>
- 모달마다 스타일 다른부분 나중에 거슬리면 일괄적으로 처리예정
- Issue: #
> ✨[#62] Feat : review-create-modal 개발완료

- src/layout/footer/Footer.tsx
- src/layout/footer/FooterCss.ts
- footer개발
<br/>
<br/>
- Issue: #74
> ✨[#74] Feat : footer개발

- src/pages/aidrq-modify-page/index.tsx
- src/pages/aidrq-modify-page/indexCss.ts
- src/pages/aidrq-modify-page/ui/info-modify/index.tsx
- src/pages/aidrq-modify-page/ui/info-modify/indexCss.ts
- src/pages/aidrq-modify-page/ui/location-modify/index.tsx
- src/pages/aidrq-modify-page/ui/location-modify/indexCss.ts
- src/pages/main-page/MainPage.tsx
- 도움요청글 수정페이지 ui개발 완료
<br/>
<br/>
- 수정페이지 이동시에 api get해서 뿌려주는 것 해야함
- 수정 시에 api보내고, 다시 get하는 것 해야함
- 라우팅 처리 해야함
- Issue: #81
> ✨[#81]Feat : 도움요청글 수정페이지 ui 개발 완료

- src/api/routes/index.tsx
- src/layout/header/Header.tsx
> 🚑️ [#96] Fix: routing 수정

- .github/workflows/CICD.yml
- .github/workflows에 CICD.yml 파일이 추가 되었습니다.
프로젝트의 빌드와 빌드가 통과된다면 s3에 자동으로 배포가 이루어지도록 설정해두었습니다.
<br/>
<br/>
- 추후에 지속적으로 업데이트가 있을 예정입니다.
- Issue: #98 
현재 간단하게 s3에 파일을 올리는 정도로만 구현을 한 상태입니다.
배포 방식에 변경이 생긴다면 말씀드리도록 하겠습니다 감사합니다.
> [#98]Feat: 배포 자동화 workflow 작성

- src/features/aidreq-detail-center-profile/_components/button-container/index.tsx
- src/features/aidreq-detail-center-profile/_components/info-container/index.tsx
- src/features/aidreq-detail-center-profile/_components/picture-container/index.tsx
- src/features/aidreq-detail-center-profile/index.tsx
- src/pages/aidrq-detail-page/index.tsx
- src/pages/aidrq-detail-page/logic/fetchAidRqDetail.ts
- src/pages/aidrq-detail-page/logic/fetchCenterProfile.ts
- src/shared/types/aidrq-detail/aidrqDetailType.ts
- src/shared/types/center-profile/centerProfile.ts
- vite.config.ts
- aidrq디테일페이지 api 연결 및 뿌리기 (명세에 맞게)
- 기존의 봉사활동글 상세조회에 포함되어 있던 center data를 분리해서 api 따로 호출
- centerProfile 타입 명세에 맞게 수정
- env파일 추가
- viteconfig에 server 3000으로 수정
<br/>
<br/>
- Issue: #
> ✨feat : aidrq디테일페이지 api 1차 연결 완료 (리스트부분 연결되면 이어서 작업할 예정)

- src/features/login-feature/_components/person-login/index.tsx
- src/features/profile-page-img-box/index.tsx
- CICD디버깅
- 로그인 테스트 가능한 상태로 변경
<br/>
<br/>
- Issue: #
> 🐛Fixed: CICD오류 디버깅

- src/pages/admin-aidrq-list-page/_components/aidrqlistadmin-wrapper/index.tsx
- CICD오류 디버깅
<br/>
<br/>
- Issue: #
> 🐛bug:CICD오류 디버깅

- src/api/routes/index.tsx
- src/features/community-create-box/index.tsx
- src/features/community-create-box/indexCss.ts
- src/pages/community-create-page/index.tsx
- src/pages/community-create-page/indexCss.ts
- 커뮤니티 작성 페이지 UI 구현 했습니다!
<br/>
<br/>
- 기능 구현 및 api 연결은 한꺼번에 하겠습니다!
- Issue: #110
> 110 feature community create page

- src/components/aidreq-list-Item/index.tsx
- src/components/aidreq-list-Item/ui/top/index.tsx
- src/components/search-bar/filter-search/ui/filter-box/index.tsx
- src/features/aidrq-create-shared-part/index.tsx
- src/features/aidrq-list-admin/index.tsx
- src/features/aidrq-list-main-page/index.tsx
- src/pages/aidrq-create-page/index.tsx
- src/pages/aidrq-detail-page/ui/title/index.tsx
- src/pages/aidrq-list-page/ui/aidrqlist-wrapper/index.tsx
- src/pages/aidrq-list-page/ui/aidrqlist-wrapper/indexCss.ts
- src/pages/aidrq-list-page/ui/search/index.tsx
- src/pages/aidrq-list-page/ui/tab/index.tsx
- src/shared/mapping/aidrq-category-mapping.ts
- src/shared/types/aidrq-create-type/AidRqCreateType.ts
- src/shared/types/aidrq-detail/aidrqDetailType.ts
- src/shared/types/aidrq-list-item/aidrqListItemType.ts
- src/store/stores/search/searchStore.ts
- aidrqlistpage 2차개발 완료
- type -> category로 변경
- 활동유형 한글->영문 매핑처리
- tab연결
<br/>
<br/>
- category로 이름 변경한 부분 미처 발견 못한 부분은 CICD오류 나면 디버깅 하겠음.
- 활동유형부분 오류 개선
- 3차 개발 필요
- Issue: #121
> ✨feat : aidrqlistpage 2차개발 완료

- src/components/aidrq-create-location/index.tsx
> 🐛 [#127] Fix: import 방식 변경

- .github/workflows/CICD.yml
- 유진님이 요청하셨던 환경변수 추가 업데이트 입니다.
<br/>
<br/>
- Issue: #
> cicd: 환경변수 추가

- src/features/alert/index.tsx
- src/layout/header/Header.tsx
- Header부분에 SSE연결 설정 완료
<br/>
<br/>
- 백엔드에서 SSE 작업 완료하면 테스트 해볼 예정
- Issue: #
> ✨[#135]Feat : 알림 SSE연결 설정 완료

- src/store/stores/admin-search/searchStore.ts
- src/store/stores/search/searchStore.ts
- store의 admin search store과 search store의 region 타입에 null 값을 추가해주었습니다. 
<br/>
<br/>
- Issue: #
> 🚑️ [#139] HotFix: search store region 타입에 null 추가

- src/features/aidrq-list-main-page/index.tsx
- src/features/aidrq-list-main-page/logic/fetchListShort.ts
- src/pages/aidrq-detail-page/logic/fetchAidRqDetail.ts
- src/pages/aidrq-detail-page/logic/fetchCenterProfile.ts
- src/pages/main-page/MainPage.tsx
- src/pages/main-page/_components/aidrq-recent-list/index.tsx
- src/pages/main-page/_components/ranking/index.tsx
- src/pages/main-page/_components/ranking/logic/fetchRanking.ts
- src/pages/main-page/_components/ranking/ui/rank-item/index.tsx
- src/shared/types/ranking-data/RankingDataType.ts
- mainpage 1차 개발완료
- 작성섹션 옵션
- 최신리스트 3개 노출
- 랭킹api연결 및 뿌려주기
<br/>
<br/>
- Issue: #
> ✨[#144]Feat: mainpage-api연결 1차작업 개발완료

- src/features/aidrq-list-main-page/index.tsx
- src/features/aidrq-list-main-page/logic/fetchListShort.ts
- src/main.tsx
- src/pages/aidrq-detail-page/logic/fetchAidRqDetail.ts
- src/pages/aidrq-detail-page/logic/fetchCenterProfile.ts
- src/pages/main-page/MainPage.tsx
- src/pages/main-page/_components/aidrq-recent-list/index.tsx
- src/pages/main-page/_components/community/index.tsx
- src/pages/main-page/_components/community/logic/fetchMainCommunity.ts
- src/pages/main-page/_components/ranking/index.tsx
- src/pages/main-page/_components/ranking/logic/fetchRanking.ts
- src/pages/main-page/_components/ranking/ui/rank-item/index.tsx
- src/shared/hooks/useInfiniteAidRq.ts
- src/shared/types/ranking-data/RankingDataType.ts
- mainpage api연결완료
<br/>
<br/>
- Issue: #
> ✨[#144]Feat/mainpage api연결 작업완료

- src/features/aidreq-detail-center-profile/_components/info-container/index.tsx
- src/features/center-profile-prefer-item-box/index.tsx
- src/features/review-read-modal/index.tsx
- src/pages/center-profile-page/_component/logic/useCenterProfile.ts
- src/shared/types/center-profile/centerProfile.ts
- src/store/queries/center-mypage/useReview.ts
> 🚑️ Fix: cicd 오류 수정

- src/features/aidreq-detail-center-profile/_components/button-container/index.tsx
- src/features/login-feature/_components/org-login/logic/testLoginCenter.ts
- src/features/login-feature/_components/org-login/logic/useOrgLogin.ts
- src/features/login-feature/_components/person-login/index.tsx
- src/features/login-feature/_components/person-login/logic/testLoginPerson.ts
- src/pages/aidrq-detail-page/index.tsx
- src/pages/aidrq-detail-page/logic/myPresentStatus.ts
- src/store/stores/login/loginStore.ts
> ✨feat:목업로그인 아이디변경

- src/pages/aidrq-detail-page/index.tsx
- src/pages/aidrq-detail-page/indexCss.ts
- src/pages/aidrq-detail-page/logic/myPresentStatus.ts
- src/pages/main-page/_components/community/logic/fetchMainCommunity.ts
- 도움요청글 디테일페이지 api연결완료
- center / person 여부에 따라 리뷰/지원 버튼 노출여부 결정
- person이 지원을 한 경우에는 지원버튼 disable처리
- person이 지원을 했더라도 admitted된 상태가 아니면 리뷰버튼 disable처리 (지금은 리뷰 구현을 위해 스타일만 disable이고 클릭은 됨)
<br/>
<br/>
- 쪽지연결
- Issue: #168
> ✨[#168]Feat:aidrq디테일페이지 개발 3차

- src/components/aidrq-create-date/index.tsx
- src/components/aidrq-create-location/index.tsx
- src/features/aidrq-create-shared-part/index.tsx
- src/features/aidrq-create-shared-part/ui/select-container/index.tsx
- src/pages/aidrq-create-page/index.tsx
- src/pages/aidrq-create-page/logic/postAidRq.ts
- src/pages/aidrq-create-page/ui/location/index.tsx
- src/pages/aidrq-create-page/ui/volunteer-date/index.tsx
- src/shared/types/aidrq-create-type/AidRqCreateType.ts
- 도움요청글 작성api개발
<br/>
<br/>
- Issue: #
> ✨[#170]feat:aidrq작성 api개발

- src/pages/aidrq-modify-page/ui/location-modify/index.tsx
- 수정페이지에 동일하게 사용하던 컴포넌트에 props를 바꿔서 일어난 오류
<br/>
<br/>
- Issue: #
> 🐛fix:cicd오류 디버깅

- src/components/aidrq-create-location/index.tsx
- src/pages/aidrq-modify-page/index.tsx
- src/pages/aidrq-modify-page/logic/fetchAidRqDefault.ts
- src/pages/aidrq-modify-page/ui/location-modify/index.tsx
- src/pages/aidrq-modify-page/ui/location-modify/logic/modifyAidRqLocation.ts
- src/shared/types/aidrq-detail/aidrqDetailType.ts
- 수정기능 중, 위치 수정기능 완료.
<br/>
<br/>
- Issue: #
> ✨feat:aidrq수정페이지 1차작업완료-location수정

- src/features/login-feature/_components/person-login/index.tsx
- src/layout/header/Header.tsx
- src/layout/header/logic/centerLogout.ts
- src/layout/header/logic/personLogout.ts
> ✨Feat: 로그인테스트

- src/pages/aidrq-create-page/ui/location/index.tsx
> ✨Bug:cicd디버깅

- src/features/login-feature/_components/org-login/logic/testLoginCenter.ts
- src/features/login-feature/_components/org-login/logic/useOrgLogin.ts
- src/features/login-feature/_components/person-login/index.tsx
- src/pages/main-page/MainPage.tsx
- 로그인 모킹 주석처리
- 로그인 실제 구현
- 테스트 1차
<br/>
<br/>
- Issue: #
> ✨feat:로그인구현테스트1차

- src/pages/main-page/MainPage.tsx
> ✨feat:로그인2차테스트

- src/api/apis/index.tsx
> ✨feat: 토큰 오류 수정

- src/features/login-feature/_components/org-login/logic/testLoginCenter.ts
> ✨fix:center로그인데이터구조변경

- package.json
- src/layout/header/Header.tsx
- src/pages/main-page/MainPage.tsx
- yarn.lock
> ✨fix:login디버깅3차

- src/components/interest-heart/logic/useInterest.ts
- src/layout/header/Header.tsx
- src/pages/aidrq-detail-page/index.tsx
- src/pages/main-page/MainPage.tsx
- src/pages/main-page/_components/localTestBox/index.tsx
- src/pages/main-page/_components/localTestBoxVolun/index.tsx
- src/store/stores/login/loginStore.ts
> ✨feat:로컬테스트용 로그인모킹 복구

- src/components/write-aidreq-button/index.tsx
- src/pages/main-page/_components/localTestBox/index.tsx
> [#206] fix: secure: true로 변경

- src/pages/main-page/_components/localTestBoxVolun/index.tsx
> 봉사자도 secrue: true

- src/layout/header/logic/centerLogout.ts
- src/layout/header/logic/personLogout.ts
- src/pages/aidrq-detail-page/logic/applyAidRq.ts
- src/pages/main-page/_components/localTestBox/index.tsx
- src/pages/main-page/_components/localTestBoxVolun/index.tsx
> ✨feat: api요청설정 및 모킹로그인과 userinfoapi연결

- src/components/inputBox/index.tsx
- src/components/inputBox/logic/useInput.ts
- src/pages/aidrq-create-page/logic/postAidRq.ts
- src/pages/aidrq-detail-page/logic/applyAidRq.ts
- src/pages/main-page/_components/localTestBox/index.tsx
- 지원하기 및 등록하기 테스트 성공
<br/>
<br/>
- Issue: #
> ✨feat:지원하기 및 등록하기 api 수정 완료

- src/features/communitiy-detail-content-box/logic/useCommunityDetailContent.ts
- src/pages/personal-my-page/_component/PMPGTop.tsx
- src/pages/personal-my-page/_component/logic/useMyProfileData.ts
- 코드 오류 고쳤습니당
<br/>
<br/>
- Issue: #216
> 🐛 CICD 오류 해결

- src/features/communitiy-detail-comment-box/logic/fetchCommunityComment.ts
- src/features/communitiy-detail-comment-box/logic/useCommunityComment.ts
- src/features/communitiy-detail-comment-box/ui/CommentCss.ts
- src/features/communitiy-detail-comment-box/ui/CommentReplyInput.tsx
- src/features/communitiy-detail-comment-box/ui/logic/useComment.ts
- src/features/community-list/index.tsx
- src/features/community-list/logic/fetchCommunityList.ts
- src/features/community-list/logic/useCommunityList.ts
- src/pages/main-page/_components/community/index.tsx
- src/pages/personal-my-page/_component/logic/fetchMyData.ts
- src/styles/global.ts
- api 부를때 page=0부터 부르도록
- 메인페이지에서 커뮤니티 글 누르면 이동안됨
- 댓글 textarea 폰트 및 Css 수정
<br/>
<br/>
- Issue: #
> 🐛 [#217] Bug: 수정완료

- src/pages/main-page/MainPage.tsx
> ✨feat:토큰수정테스트

- src/layout/header/logic/centerLogout.ts
- src/layout/header/logic/personLogout.ts
- src/pages/aidrq-create-page/logic/postAidRq.ts
- src/pages/aidrq-detail-page/logic/applyAidRq.ts
> ✨feat:토큰테스트/지원하기등록하기테스트

- src/features/alert/index.tsx
- src/layout/header/Header.tsx
- src/layout/header/HeaderCss.ts
- Header에 로그인버튼/로그아웃버튼/마이페이지 등을 로그인 여부에 따라 노출을 다르게 했음
- SSE 요청에 token을 자동헤더로 변경했고, console에 찍히는 data구조를 보고 2차로 테스트 예정
<br/>
<br/>
- Issue: #
> ✨feat:Header설정 및 sse1차테스트

- src/components/textArea/index.tsx
- src/features/communitiy-detail-comment-box/logic/fetchCommunityComment.ts
- src/features/communitiy-detail-content-box/logic/fetchCommunityDetailContent.ts
- src/features/communitiy-detail-content-box/logic/useCommunityDetailContent.ts
- src/features/community-create-box/index.tsx
- src/features/community-create-box/logic/postCommunity.ts
- src/features/community-create-box/logic/useCreateCommunity.ts
- src/features/community-list/index.tsx
- src/shared/types/resType.ts
- 커뮤니티 글 생성 페이지 api 연결 (/communitycreate)
- 수정하기의 경우 자신이 쓴 글인지 확인 (/communitycreate/{content_id})
- 내가 작성한 글이 아니면 alert 후 list page로 이동
<br/>
<br/>
- Issue: #180
> 180 feature community create page api 연결

- src/layout/header/Header.tsx
- src/pages/main-page/MainPage.tsx
> sse세부디버깅 및 로그인버그개선

- src/features/communitiy-detail-comment-box/logic/fetchCommunityComment.ts
> 🐛 [#231] BUG: CICD error fix

- src/api/routes/index.tsx
- src/layout/header/Header.tsx
- src/layout/header/HeaderCss.ts
- 마이페이지 라우팅처리
- sse 디버깅
<br/>
<br/>
- Issue: #
> ✨feat:마이페이지라우팅처리 및 sse디버깅

- src/components/write-aidreq-button/index.tsx
- src/features/aidreq-detail-admin-info/_components/applicant-status/index.tsx
- src/features/aidrq-list-admin/index.tsx
- src/features/manage-center-post-set/_components/go-aidreq-set/index.tsx
- src/pages/aidrq-detail-admin-page/ui/button-group/index.tsx
- centermypage로 이동하는 모든 navigate를 일반 mypage로 변경함
<br/>
<br/>
- Issue: #
> 🐛fix:centermypage라우팅수정

- src/components/aidrq-create-date/index.tsx
- src/components/aidrq-create-recruit-population/index.tsx
- src/components/select/index.tsx
- src/features/aidrq-create-shared-part/index.tsx
- src/features/aidrq-create-shared-part/ui/select-container/index.tsx
- src/pages/aidrq-create-page/index.tsx
- src/pages/aidrq-create-page/ui/recruit-population/index.tsx
- src/pages/aidrq-create-page/ui/volunteer-date/index.tsx
- src/pages/aidrq-detail-admin-page/index.tsx
- src/pages/aidrq-detail-admin-page/ui/button-group/index.tsx
- src/pages/aidrq-modify-page/index.tsx
- src/pages/aidrq-modify-page/ui/info-modify/index.tsx
- src/pages/aidrq-modify-page/ui/info-modify/logic/modifyAidRqRegular.ts
- src/pages/aidrq-modify-page/ui/location-modify/index.tsx
- src/pages/aidrq-modify-page/ui/location-modify/logic/modifyAidRqLocation.ts
- 수정하기페이지 개발
- 재사용컴포넌트 수정에 따른 props수정
<br/>
<br/>
- Issue: #
> ✨[#239]feat:수정하기페이지 개발

- src/components/alert-item/index.tsx
- src/features/alert/index.tsx
- src/features/alert/logic/single-read/index.ts
- notification연결 및 읽기기능 구현
<br/>
<br/>
- Issue: #
> ✨feat:notification연결및읽기기능구현

- src/components/alert-item/index.tsx
- src/components/alert-item/indexCss.ts
- src/features/alert/index.tsx
- src/layout/header/Header.tsx
- src/layout/header/HeaderCss.ts
- src/shared/types/alert-type/AlertType.ts
- notification정보를 header 컴포넌트 단에서 관리하도록 수정
- header에서 항상 업데이트 (알림 오면 바로 업데이트)
- Alert아이콘에 notification이 있는경우 '알림존재'표시
<br/>
<br/>
- Issue: #
> ✨feat:notification작업완료

- src/pages/center-profile-page/_component/CPPGReviewList.tsx
> 센터프로필페이지 부분 안쓰이는 곳 주석처리

- src/features/review-create-modal/index.tsx
- src/features/review-create-modal/logic/createReview.ts
- src/features/review-create-modal/logic/handleFileSelect.ts
> ✨feat:리뷰구현

- src/features/communitiy-detail-comment-box/logic/useCommunityComment.ts
- src/pages/center-profile-page/_component/logic/useCenterReview.ts
> 🐛 [#253] BUG: CICD Fix

- src/features/communitiy-detail-comment-box/logic/fetchCommunityComment.ts
- src/features/message-create-modal/logic/postMessage.ts
- src/features/message-create-modal/logic/useSendMail.ts
- src/features/profile-page-img-box/index.tsx
> 228 feature 기관 개인 프로필 페이지 쪽지 api 연결

- src/features/review-create-modal/index.tsx
- src/features/review-create-modal/logic/createReview.ts
- src/pages/aidrq-detail-page/index.tsx
> ✨feat:리뷰 수정

- src/components/interest-heart/logic/putInterest.ts
- src/features/communitiy-detail-comment-box/logic/useCommunityComment.ts
- src/features/communitiy-detail-comment-box/ui/logic/useCommentReplyInput.ts
- src/features/communitiy-detail-content-box/logic/useCommunityDetailContent.ts
- src/features/communitiy-detail-content-box/ui/WriterProfileBox.tsx
- src/features/community-create-box/logic/postCommunity.ts
- src/features/community-list/logic/useCommunityList.ts
- src/features/message-read-modal/index.tsx
- src/features/personal-my-page-edit-profile/logic/putMyProfile.ts
- src/features/personal-my-page-edit-profile/logic/useEditMyProfile.ts
- src/features/personal-my-page-half-list/index.tsx
- src/features/personal-my-page-half-list/logic/useHalfList.ts
- src/features/personal-my-page-interest-center-list/_component/InterestCenterBox.tsx
- src/features/personal-my-page-interest-center-list/_component/InterestCenterBoxCss.ts
- src/features/personal-my-page-interest-center-list/index.tsx
- src/features/personal-my-page-interest-center-list/logic/useMyInterestCenter.ts
- src/features/personal-my-page-review-list/logic/useMyReview.ts
- src/features/profile-page-img-box/index.tsx
- src/features/profile-page-info-box/index.tsx
- src/pages/center-profile-page/_component/logic/useCenterProfile.ts
- src/pages/center-profile-page/_component/logic/useCenterReview.ts
- src/pages/personal-my-page/_component/logic/useMyProfileData.ts
- src/pages/personal-profile-page/logic/usePersonProfile.ts
- src/store/queries/center-mypage/useReview.ts
- tier 수정
- header에 Authorization 삭제
- 개인마이페이지 프로필 put 오류 해결
- 등 자잘한 버그
<br/>
<br/>
- Issue: #
> 257 fix 개인마이페이지 버그 수정

- src/components/alert-item/index.tsx
- src/features/alert/index.tsx
- src/layout/header/Header.tsx
- src/shared/types/alert-type/AlertType.ts
- 리뷰 수정
- notification type에 따라 페이지이동 처리
- 알림 읽음기능 수정
<br/>
<br/>
- Issue: #
> ✨feat: notification수정

- src/pages/aidrq-detail-page/index.tsx
- src/pages/aidrq-detail-page/logic/applyAidRq.ts
- src/pages/main-page/MainPage.tsx
- src/pages/main-page/MainpageCss.ts
메인페이지수정 및 디테일페이지 분류
<br/>
<br/>
- Issue: #
> ✨[#264]Feat:메인페이지수정 및 디테일페이지 분류

- src/features/main-banner/indexCss.ts
- src/layout/header/Header.tsx
- src/pages/aidrq-list-page/ui/aidrqlist-wrapper/index.tsx
- src/pages/main-page/_components/ranking/ui/rank-item/index.tsx
- 이미지사라짐오류디버깅
- 리스트 status오류디버깅
<br/>
<br/>
- Issue: #
> 🐛이미지사라짐오류디버깅/status오류디버깅

- src/features/aidreq-detail-center-profile/_components/info-container/index.tsx
- src/pages/aidrq-detail-page/index.tsx
- src/pages/aidrq-detail-page/indexCss.ts
- src/shared/types/center-profile/centerProfile.ts
> 🐛[#271]Fix:지원물품리스트 및 지원하기버튼css 디버깅

- src/components/interest-heart/index.tsx
- src/components/interest-heart/logic/useInterest.ts
- src/features/message-create-modal/logic/postMessage.ts
- src/features/message-create-modal/logic/useSendMail.ts
- src/features/profile-page-img-box/index.tsx
- src/pages/main-page/_components/community/indexCss.ts
- src/shared/types/center-profile/centerProfile.ts
> 262 fix 쪽지 관심기관 하트 api 연결 오류

- src/api/routes/index.tsx
- src/layout/header/Header.tsx
- 로컬스토리지 정보에 따라 랜딩페이지 연결
<br/>
<br/>
- Issue: #
> ✨feat:랜딩페이지연결

- src/features/manage-center-post-set/_components/message-set/index.tsx
- src/features/message-read-modal/index.tsx
- src/store/queries/center-mypage/useMessage.ts
> 🐛 [#283] Fix: 쪽지 읽음처리 ui 즉시 반영으로 수정

- src/features/community-list/logic/useCommunityList.ts
> 🐛 커뮤니티 리스트 CICD 오류 수정

- src/features/aidreq-detail-admin-recruit-state/index.tsx
- src/pages/aidrq-detail-admin-page/index.tsx
- src/store/queries/aidreq-detail-center/useApplicantStatus.ts
- 지원자 현황 부분에 통계 api를 호출해서 total로 데이터 변
<br/>
<br/>
- Issue: #
> 🐛 [#291] Fix: 데이터 바인딩 변경

- src/store/queries/community-detail-common-query/useCommunityComment.ts
- 주석처리
<br/>
<br/>
- resType에 content부분 추가하기
- Issue: #300
> 🐛bug:CICD오류개선

- src/features/community-list/index.tsx
- src/features/community-list/logic/useCommunityList.ts
- src/store/queries/community-list-common-query/useCommunityList.ts
- community list부분 react query로 변경
<br/>
<br/>
- Issue: #
> ✨feat:communitylist reactquery로 변경

- src/features/aidrq-list-main-page/index.tsx
- src/store/queries/main-page-common-query/useFetchMainCommunity.ts
- src/store/queries/main-page-common-query/useFetchRanking.ts
- src/store/queries/main-page-common-query/useListShort.ts
> store/queries/main-page-common-query
- axiosInstance, react-query 사용하도록 수정했습니다
- 로컬에서 작동하는거 확인했습니다
- 
<br/>
<br/>
- Issue: #303
> react query로 변경 test

- src/features/aidreq-detail-info/_components/current-recruit/index.tsx
- src/pages/aidrq-detail-page/index.tsx
- src/store/queries/aidreq-detail-volunteer-query/useApplyAidRq.ts
- src/store/queries/aidreq-detail-volunteer-query/useCurrentRecruitment.ts
- src/store/queries/aidreq-detail-volunteer-query/useFetchAidRqDetail.ts
- src/store/queries/aidreq-detail-volunteer-query/useFetchCenterProfile.ts
- src/store/queries/aidreq-detail-volunteer-query/usePresentStatus.ts
- 디테일페이지 - 센터프로필 불러오기 reactquery 처리
- 디테일페이지 - 디테일정보 불러오기 reactquery 처리
- 디테일페이지 - 지원하기 reactquery 처리
- 디테일페이지 - 모집글 지원자 단건 조회 api 변경에 따른 조건 변경 (200/210 에서 200/400으로)
<br/>
<br/>
- Issue: #
> ✨feat: aidrq detail기능 reactquery로 변경

- src/components/aidrq-create-recruit-population/index.tsx
- src/pages/aidrq-create-page/index.tsx
- src/pages/aidrq-modify-page/index.tsx
- src/pages/aidrq-modify-page/ui/info-modify/index.tsx
- src/pages/aidrq-modify-page/ui/location-modify/index.tsx
- src/store/queries/aidreq-control-center-query/useFetchAidRqDefault.ts
- src/store/queries/aidreq-control-center-query/useModifyAidRqRegular.ts
- src/store/queries/aidreq-control-center-query/usePostAidRq.ts
- src/store/queries/aidreq-detail-volunteer-query/useApplyAidRq.ts
- src/store/queries/aidreq-detail-volunteer-query/useFetchAidRqDetail.ts
- aidrq post부분 react query처리
- aidrq modify default get부분 react query처리
<br/>
<br/>
- Issue: #
> ✨feat: aidrq post부분과 modify default get부분 react query처리

- src/features/aidreq-detail-admin-info/_components/applicant-status/index.tsx
- src/features/aidreq-detail-admin-info/indexCss.ts
- src/features/edit-center-profile/_components/profile-edit-form/index.tsx
- src/features/edit-center-profile/_components/profile-edit-form/indexCss.ts
- src/features/edit-center-profile/index.tsx
- src/features/edit-center-profile/indexCss.ts
- src/features/manage-center-post-set/_components/go-aidreq-set/index.tsx
- src/features/manage-center-post-set/_components/go-aidreq-set/indexCss.ts
- src/features/register-goods/_components/register-bar/index.tsx
- src/features/register-goods/_components/register-bar/indexCss.ts
- src/features/register-goods/index.tsx
- src/pages/aidrq-detail-admin-page/ui/button-group/index.tsx
- src/pages/aidrq-detail-admin-page/ui/button-group/indexCss.ts
- 기관 마이페이지 프로필 수정 부분 디자인 시안대로 퍼블리싱 변경
- 버튼에 컴포넌트 적용
<br/>
- api 연결
- Issue: #317
> ♻️ [#317] Refactor: 기관 마이페이지, 버튼 컴포넌트 적용

- src/components/applicant-list-item/index.tsx
- src/components/applicant-list-item/indexCss.ts
- src/components/search-bar/filter-search/ui/filter-box/index.tsx
- src/components/search-bar/filter-search/ui/filter-box/indexCss.ts
- src/components/search-bar/nonfilter-search/index.tsx
- src/components/search-bar/nonfilter-search/indexCss.ts
- src/components/write-aidreq-button/index.tsx
- src/components/write-aidreq-button/indexCss.ts
- src/features/aidreq-detail-center-profile/_components/button-container/index.tsx
- src/features/aidreq-detail-center-profile/_components/button-container/indexCss.ts
- src/pages/aidrq-create-page/index.tsx
- src/pages/aidrq-create-page/indexCss.ts
- src/pages/aidrq-detail-page/index.tsx
- src/pages/aidrq-detail-page/indexCss.ts
- src/pages/aidrq-modify-page/ui/info-modify/index.tsx
- src/pages/aidrq-modify-page/ui/info-modify/indexCss.ts
- src/pages/aidrq-modify-page/ui/location-modify/index.tsx
- src/pages/aidrq-modify-page/ui/location-modify/indexCss.ts
- Button컴포넌트 재사용
<br/>
<br/>
- 안된부분 보일때마다 수정하기
- Issue: #
> 318 feature button컴포넌트 재사용하기

- src/features/communitiy-detail-comment-box/index.tsx
- src/features/communitiy-detail-comment-box/logic/useCommunityComment.ts
- src/features/communitiy-detail-comment-box/ui/Comment.tsx
- src/features/communitiy-detail-comment-box/ui/CommentReplyInput.tsx
- src/features/communitiy-detail-comment-box/ui/logic/useComment.ts
- src/features/communitiy-detail-comment-box/ui/logic/useCommentReplyInput.ts
- src/features/communitiy-detail-content-box/logic/useCommunityDetailContent.ts
- src/features/community-create-box/logic/useCreateCommunity.ts
- src/pages/community-create-page/index.tsx
- src/store/queries/community-create-common-query/useControlCommunity.ts
- src/store/queries/community-detail-common-query/useCommunityComment.ts
- src/store/queries/community-detail-common-query/useCommunityDetailContent.ts
- src/store/queries/main-page-common-query/useListShort.ts
- community 부분 react query 변경했습니다
- 글 작성/수정 부분에서 수정사항 있을 예정입니다
<br/>
<br/>
- Issue: #308
> 308 feature community 파트 react query 변경

- src/features/edit-center-profile/_components/profile-edit-form/index.tsx
- src/features/edit-center-profile/_components/profile-edit-form/indexCss.ts
- 프로필 이미지 섹션
- 연락처 & 사이트 섹션
- 닉네임 & 설명 섹션
으로 분리
<br/>
<br/>
- api 연결하면서 닉네임과 기관명 연결 해제
- Issue: #325
> ♻️ [#325] Refactor: 기관 마이페이지 재퍼블리싱

- src/pages/aidrq-detail-admin-page/ui/button-group/index.tsx
- src/pages/aidrq-detail-admin-page/ui/button-group/indexCss.ts
- src/store/queries/aidreq-detail-admin-query/useAidRqDetail.ts
- 삭제 버튼 요소 생성 (컴포넌트 사용 x)
- store/query/aidreq-detail-admin-query/useAidRqDetail.ts에 delete fetch 함수 추가
- src/pages/aidrq-detail-admin-page/ui/button-group/index.tsx/ButtonGroup에 handleDeleteAidRqContent 추가
<br/>
- Issue: #327
> ✨ [#327] Feature: 모집글 삭제 api 연결 완료

- src/components/interest-heart/index.tsx
- src/components/interest-heart/logic/putInterest.ts
- src/components/interest-heart/logic/useInterest.ts
- src/features/communitiy-detail-comment-box/logic/useCommunityComment.ts
- src/features/message-create-modal/logic/useSendMail.ts
- src/features/personal-my-page-edit-profile/logic/useEditMyProfile.ts
- src/features/personal-my-page-half-list/logic/useHalfList.ts
- src/features/personal-my-page-interest-center-list/logic/useMyInterestCenter.ts
- src/features/personal-my-page-review-list/logic/useMyReview.ts
- src/features/profile-page-img-box/index.tsx
- src/features/profile-page-img-box/indexCss.ts
- src/pages/center-profile-page/_component/logic/useCenterProfile.ts
- src/pages/center-profile-page/_component/logic/useCenterReview.ts
- src/pages/personal-my-page/_component/logic/useMyProfileData.ts
- src/pages/personal-profile-page/logic/usePersonProfile.ts
- src/store/queries/center-profile-query/useFetchCenterData.ts
- src/store/queries/interest-heart-query/useInterestHeart.ts
- src/store/queries/message-create-common-query/usePostMessage.ts
- src/store/queries/volunteer-mypage/useFetchMyData.ts
- src/store/queries/volunteer-mypage/usePutMyProfile.ts
- src/store/queries/volunteer-profile/useFetchPersonProfile.ts
- api에 리액트 쿼리 적용 (기관 프로필, 지원자 피로필, 지원자 마이페이지, 메시지 생성, 관심기관)
- 프로필 페이지 버튼 컴포넌트 수정
<br/>
<br/>
- Issue: #322
> Refactor: 리액트 쿼리 나머지 적용

- src/components/interest-heart/logic/useInterest.ts
- src/store/stores/interest-center/interestStore.ts
- 관심기관 등록/삭제 기능 구현 완료
<br/>
<br/>
- Issue: #
> ✨feat:관심기관 기능 구현완료

- src/layout/header/Header.tsx
- src/store/queries/aidreq-detail-volunteer-query/usePresentStatus.ts
- 모집글 지원 단건 조회 210코드 조건처리
- SSE및 Notification 관련 테스트 콘솔 삭제
<br/>
<br/>
- Issue: #
> 🐛fix:210에러조건처리 / SSE및notification관련 콘솔 삭제

- src/features/communitiy-detail-comment-box/ui/CommentInput.tsx
- src/features/communitiy-detail-comment-box/ui/CommentInputCss.ts
- src/features/communitiy-detail-content-box/index.tsx
- src/features/communitiy-detail-content-box/indexCss.ts
- src/features/communitiy-detail-content-box/logic/useCommunityDetailContent.ts
- src/features/communitiy-detail-content-box/ui/WriterProfileBox.tsx
- src/features/communitiy-detail-content-box/ui/WriterProfileBoxCss.ts
- src/features/community-create-box/index.tsx
- src/features/community-create-box/indexCss.ts
- src/features/community-create-box/logic/useCreateCommunity.ts
- src/features/community-list/index.tsx
- src/features/community-list/indexCss.ts
- src/features/review-read-modal/index.tsx
- src/store/queries/community-create-common-query/useControlCommunity.ts
- src/store/queries/volunteer-profile/useFetchPersonProfile.ts
- src/store/queries/volunteer-profile/useVolunteerProfile.ts
- 커뮤니티 오류 수정
- 버튼 css 추가
<br/>
<br/>
- Issue: #331
> 331 fix 오류 수정

- src/pages/main-page/_components/ranking/ui/rank-item/index.tsx
- src/pages/main-page/_components/ranking/ui/rank-item/indexCss.ts
- 프로필 닉네임  p 태그를 react-router-dom의 Link 태그로 변경
- /profile/${item.volunteer_id}로 라우팅 변경
- Issue: #344
> ✨ [#344] Feat: 봉사왕 프로필 연결 완성

- src/components/alert-item/index.tsx
- src/components/alert-item/indexCss.ts
- src/features/alert/index.tsx
- src/features/alert/indexCss.ts
- src/features/alert/logic/all-read/deleteAllNotifications.ts
- src/layout/header/Header.tsx
- 알림 클릭 시, 페이지 이동 처리 완료
- 알림창 이외 클릭 시, 알림 닫히기 처리 완료
- 알림 전체삭제기능 구현 완료
<br/>
<br/>
- Issue: #
> ✨feat:알림기능추가구현완료

- src/components/inputBox/index.tsx
- src/components/inputBox/indexCss.ts
- src/components/inputBox/logic/useInput.ts
- src/components/search-bar/filter-search/index.tsx
- src/components/search-bar/nonfilter-search/index.tsx
- src/components/textArea/index.tsx
- src/components/textArea/indexCss.ts
- src/components/textArea/logic/useInput.ts
- src/features/aidrq-create-shared-part/index.tsx
- src/features/communitiy-detail-comment-box/ui/CommentInput.tsx
- src/features/community-create-box/index.tsx
- src/features/find-nearby-activity-search/index.tsx
- src/features/input-with-label/InputWithLabel.tsx
- src/features/login-feature/_components/org-login/index.tsx
- src/features/message-create-modal/index.tsx
- src/features/review-create-modal/index.tsx
- src/pages/aidrq-create-page/ui/explanation/index.tsx
- src/pages/aidrq-modify-page/ui/info-modify/index.tsx
- src/pages/center-contact-page/ui/contact-form/index.tsx
- 유진님이 Button 컴포넌트 만드신 것 참고해서 수정했습니다.
- InputBox와 TextArea 컴포넌트 사용된 부분에 모두 주석 넣어두었습니다.
- 둘다 기본 width 는 100%로 설정해뒀습니다
- 기존에 사용하던 함수는 건드리지 않았습니다! (getInputText함수는 옵셔널하게 변경)
<br/>
<br/>
- Issue: #343
> inputBox & textArea 컴포넌트 수정

- src/components/inputBox/index.tsx
- src/components/inputBox/indexCss.ts
- src/components/inputBox/logic/useInput.ts
- src/components/search-bar/filter-search/index.tsx
- src/components/search-bar/nonfilter-search/index.tsx
- src/components/textArea/index.tsx
- src/components/textArea/indexCss.ts
- src/components/textArea/logic/useInput.ts
- src/features/aidrq-create-shared-part/index.tsx
- src/features/communitiy-detail-comment-box/ui/CommentInput.tsx
- src/features/community-create-box/index.tsx
- src/features/find-nearby-activity-search/index.tsx
- src/features/input-with-label/InputWithLabel.tsx
- src/features/login-feature/_components/org-login/index.tsx
- src/features/message-create-modal/index.tsx
- src/features/personal-my-page-edit-profile/index.tsx
- src/features/review-create-modal/index.tsx
- src/pages/aidrq-create-page/ui/explanation/index.tsx
- src/pages/aidrq-modify-page/ui/info-modify/index.tsx
- src/pages/center-contact-page/ui/contact-form/index.tsx
- CICD 고쳤습니다!
<br/>
<br/>
- Issue: #
> CICD 오류 해결

- src/components/aidreq-list-Item/index.tsx
- src/components/aidreq-list-Item/ui/bottom/index.tsx
- src/components/aidrq-create-date/index.tsx
- src/components/aidrq-create-hours/index.tsx
- src/components/aidrq-create-hours/indexCss.ts
- src/components/search-bar/filter-search/index.tsx
- src/components/search-bar/filter-search/ui/filter-box/index.tsx
- src/components/search-bar/nonfilter-search/index.tsx
- src/components/textArea/indexCss.ts
- src/features/aidreq-detail-admin-info/_components/activity-time/index.tsx
- src/features/aidreq-detail-admin-info/index.tsx
- src/features/aidreq-detail-info/_components/volunteer-date/index.tsx
- src/features/review-create-modal/index.tsx
- src/pages/aidrq-create-page/index.tsx
- src/pages/aidrq-create-page/ui/explanation/index.tsx
- src/pages/aidrq-create-page/ui/volunteer-hour/index.tsx
- src/pages/aidrq-create-page/ui/volunteer-hour/indexCss.ts
- src/pages/aidrq-detail-page/index.tsx
- src/shared/types/aidrq-create-type/AidRqCreateType.ts
- src/shared/types/aidrq-detail/PresentResponse.ts
- src/shared/types/aidrq-detail/aidrqDetailType.ts
- src/shared/types/aidrq-list-item/aidrqListItemType.ts
- src/store/queries/aidreq-detail-volunteer-query/usePresentStatus.ts
- 모집글 등록 시, 시간 입력받도록 추가
- volunteer_time들 전부 volunteer_hours로 변경 (타입 및 response들)
- 리뷰 작성 시, aidrq id를 넘기던 것을 apply id로 변경
- 모집글 등록 시, UTC -> 한국시간으로 변경
<br/>
<br/>
- api가 완료되면, 테스트 후 수정부분도 시간수정 가능하도록 하기
- 유효성검사
- Issue: #
> ✨feat:모집글등록 기능추가 1차 / 리뷰api수정

- src/shared/types/location/nearbyLocation.ts
- volunteer_time이 아직 사용중인 곳이 있었음
<br/>
<br/>
- Issue: #
> 🐛fix:cicd오류디버깅

- src/components/inputBox/index.tsx
- src/components/textArea/index.tsx
- src/features/input-with-label/InputWithLabel.tsx
- src/features/input-with-label/InputWithLabelCss.ts
- src/features/message-create-modal/index.tsx
- src/features/message-create-modal/indexCss.tsx
- src/features/personal-my-page-edit-profile/index.tsx
- 컴포넌트에 styled 적용 안되는 문제 해결 (컴포넌트에 className props 추가하기)
<br/>
<br/>
- Issue: #356
> 🐛 Bug: 컴포넌트에 styled 적용 안되는 문제 해결

- src/features/message-read-modal/index.tsx
- src/features/message-read-modal/indexCss.ts
- src/features/review-read-modal/index.tsx
- src/features/review-read-modal/indexCss.ts
> ♻️ [#369] Refactor: 기관의 쪽지/리뷰 모달의 상세 프로필 보러가기 버튼에 컴포넌트 적용

- src/store/queries/community-detail-common-query/useCommunityDetailContent.ts
> 374 fix cicd

- src/components/aidrq-create-date/index.tsx
- src/pages/aidrq-create-page/index.tsx
- src/pages/aidrq-create-page/logic/validateVolunteerData.ts
- 모집글 등록 시 유효성 검사
<br/>
<br/>
- api완료되면 수정하기부분 마저 작업
- Issue: #
> ✨feat: 모집글 등록 시, 유효성검사

- src/features/communitiy-detail-comment-box/index.tsx
- src/features/communitiy-detail-comment-box/ui/Comment.tsx
- src/features/communitiy-detail-comment-box/ui/CommentInput.tsx
- src/features/personal-my-page-half-list/index.tsx
- src/layout/header/Header.tsx
- 개인 마이페이지 내 봉사 글 클릭시 해당 봉사로 이동하도록 수정
- 로그아웃 시 커뮤니티 댓글달기 버튼 없애기
<br/>
<br/>
- 리뷰 여부에 따라 disable처리하는 api호출
- Issue: #
> ✨fix:15/19에러수정

- public/assets/imgs/select-arrow.svg
- src/components/select/index.tsx
- src/components/select/indexCss.ts
- select컴포넌트 div로 커스텀
<br/>
<br/>
- Issue: #
> ✨feat:select컴포넌트수정

- src/features/personal-my-page-edit-profile/index.tsx
- src/features/personal-my-page-edit-profile/indexCss.ts
- 개인마이페이지 퍼블리싱만 간단히 수정했습니다!
- api 수정해주시면 버튼 기능 추가하겠습니당
<br/>
<br/>
- Issue: #383
> 383 fix 개인마이페이지 profile img 분리

- src/pages/signup-page/index.tsx
> 아직 안쓰이고 있는 state함수 제거

- package.json
- src/components/tinyMCE-editor/index.tsx
- src/features/community-create-box/index.tsx
- src/features/community-create-box/logic/useCreateCommunity.ts
- yarn.lock
- 텍스트에디터 추가했습니다(tinyMCE)
- 지금 로그인이 안 돼서 글 등록은 테스트를 못해봤고
- 이미지는 base64로 변환되어 저장되도록 되어있습니다. (추후 api 나오면 변경필요, 이미지 저장하는 주소가 아직 없어서 이미지 추가하면 에러가 에디터 내에 에러가 뜹니다)
- 현재 커뮤니티에만 적용되어있고 api 나온 후 수정하고 리뷰에도 적용하겠습니다
<br/>
<br/>
- api 나온 후 수정
- 리뷰에도 추가
- Issue: #388
> ✨ Feat: texteditor추가(tinyMCE)

- src/components/aidreq-list-Item/indexCss.ts
- src/components/search-bar/filter-search/ui/filter-box/indexCss.ts
- src/pages/aidrq-list-page/indexCss.ts
- src/pages/aidrq-list-page/ui/tab/indexCss.ts
- 도움요청글 리스트 페이지 반응형 시안 완료
<br/>
<br/>
- Issue: #
aidrq list item 컴포넌트와 filter search 컴포넌트 반응형 작업 해놨습니다
> ✨feat:aidrqlistpage 반응형 완료

- src/components/long-list-item/indexCss.ts
- src/components/long-list-item/ui/CommunityInfoCss.ts
- src/components/search-bar/nonfilter-search/index.tsx
- src/components/search-bar/nonfilter-search/indexCss.ts
- src/features/community-list/indexCss.ts
- src/pages/community-list-page/index.tsx
- 리스트 페이지 반응형 완료했습니당
<br/>
<br/>
- 커뮤니티 디테일페이지
- Issue: #403
> 403 feature 커뮤니티 리스트 페이지 반응형

- src/features/aidreq-detail-center-profile/_components/button-container/indexCss.ts
- src/features/aidreq-detail-center-profile/_components/info-container/indexCss.ts
- src/features/aidreq-detail-center-profile/_components/picture-container/indexCss.ts
- src/features/aidreq-detail-center-profile/indexCss.ts
- src/features/aidreq-detail-info/_components/recruit-date/indexCss.ts
- src/features/aidreq-detail-info/_components/volunteer-date/indexCss.ts
- src/features/aidreq-detail-info/indexCss.ts
- src/features/aidrq-list-regular/indexCss.ts
- src/pages/aidrq-detail-page/indexCss.ts
- src/pages/aidrq-detail-page/ui/text-content/indexCss.ts
- src/pages/aidrq-detail-page/ui/title/indexCss.ts
- 도움요청글 상세페이지 반응형 완료
<br/>
<br/>
- 로그인되면, 하단 버튼부분 안깨지는지 확인 필요
- Issue: #
> ✨feat:aidrq 디테일페이지 반응형 완료

- src/features/communitiy-detail-comment-box/index.tsx
- src/features/communitiy-detail-comment-box/ui/CommentCss.ts
- src/features/communitiy-detail-comment-box/ui/CommentInputCss.ts
- src/features/communitiy-detail-content-box/indexCss.ts
- src/features/communitiy-detail-content-box/ui/WriterProfileBoxCss.ts
- src/pages/community-detail-page/indexCss.ts
- 커뮤니티 디테일 페이지 반응형 적용했습니다!
<br/>
<br/>
- Issue: #408
> 408 feature 커뮤니티 디테일 페이지 반응형

- src/components/tinyMCE-editor/index.tsx
- src/features/community-create-box/indexCss.ts
- src/pages/community-create-page/indexCss.ts
- 커뮤니티 작성 페이지 반응형 적용했습니다!
<br/>
<br/>
- Issue: #412
> 412 feature 커뮤니티 작성 페이지 반응형

- src/pages/aidrq-detail-page/ui/title/indexCss.ts
- src/pages/aidrq-modify-page/index.tsx
- src/pages/aidrq-modify-page/logic/validateVolunteerData.ts
- src/pages/aidrq-modify-page/ui/info-modify/index.tsx
- src/pages/aidrq-modify-page/ui/info-modify/indexCss.ts
- src/pages/aidrq-modify-page/ui/location-modify/index.tsx
- src/store/queries/aidreq-control-center-query/useModifyAidRqLocation.ts
- 모집글 수정 시, 시간필드 추가 및 테스트
- 수정페이지에 유효성검사 추가
<br/>
<br/>
- 모집글이 종료되면 수정하기 기능을 막는 것이 어떤지??
- Issue: #
> ✨feat:모집글 수정기능 추가구현

- src/features/message-read-modal/indexCss.ts
- src/features/review-read-modal/indexCss.ts
> ✨ [#428] Feat: 기관이 조회하는 리뷰/쪽지 모달 반응형 완료

- src/components/search-bar/nonfilter-search/index.tsx
- src/features/community-list/index.tsx
- src/features/community-list/indexCss.ts
- src/features/community-list/logic/useCommunityList.ts
- src/features/custom-pagnation/index.tsx
- src/pages/community-list-page/index.tsx
- src/store/queries/community-list-common-query/useCommunityList.ts
- 쿼리스트링 사용해서 page랑 검색어를 url에서 관리하도록 수정했습니다
- 새로고침/뒤로가기 해도 페이지와 검색어가 유지됩니당
<br/>
<br/>
- Issue: #416
> 416 fix 커뮤니티 페이지네이션 유지안되는 bug

- public/assets/imgs/menu-bar.svg
- src/components/right-menu/index.tsx
- src/components/right-menu/indexCss.ts
- src/components/write-aidreq-button/indexCss.ts
- src/layout/header/Header.tsx
- src/layout/header/HeaderCss.ts
- src/pages/aidrq-modify-page/ui/info-modify/index.tsx
- src/pages/aidrq-modify-page/ui/info-modify/indexCss.ts
- header반응형 및 햄버거메뉴 구현
- 모집글작성섹션 (메인 및 기관모집글리스트 페이지) 반응형 구현
<br/>
<br/>
- Issue: #
> ✨feat:header반응형구현

- src/pages/aidrq-detail-page/index.tsx
- src/shared/types/aidrq-detail/PresentResponse.ts
- 리뷰여부에 따라 리뷰버튼 활성/비활성화
<br/>
<br/>
- Issue: #
> ✨feat:리뷰여부판별

- src/features/login-feature/_components/org-login/index.tsx
- src/features/login-feature/_components/org-login/logic/useOrgLogin.ts
- src/pages/login-page/logic/useLogin.ts
- 기존 로그인 기능을 담당하던 login-feature 주석처리
<br/>
<br/>
- Issue: #
> 🐛fix:cicd디버깅

- src/pages/login-page/LoginPage-backup.tsx
- loginpage 백업 페이지 주석처리
<br/>
<br/>
- Issue: #
> 🐛fix:cicd디버깅2차

- src/pages/admin-aidrq-list-page/indexCss.ts
- src/pages/center-my-page/indexCss.ts
- src/pages/center-profile-page/indexCss.ts
- src/pages/community-create-page/indexCss.ts
- src/pages/community-detail-page/indexCss.ts
- src/pages/community-list-page/indexCss.ts
- src/pages/personal-my-page/index.tsx
- src/pages/personal-my-page/indexCss.ts
- src/pages/personal-profile-page/indexCss.ts
- src/styles/theme.ts
- theme에 기본 css 추가해뒀습니다
- 페이지 wrapper에 가져다 사용하시면 됩니다
- 추가/변경하고 싶으신 기본 css 있으면 추가해주세요
<br/>
<br/>
- Issue: #436
> 💄 theme에 topPadding 및 기본 css 추가

- package.json
- src/layout/header/Header.tsx
- src/layout/header/HeaderCss.ts
- yarn.lock
- SSE 이벤트를 header토큰으로 전송할 수 있는 EventSourcePollyfill사용
<br/>
<br/>
- Issue: #
yarn install 한번씩 해주세요~~
> 🐛fix:EventPollyfill사용

- src/pages/login-page/LoginPage.tsx
- src/pages/login-page/logic/useLogin.ts
- 로그인 유효성 검사 실패 -> 'id와 pwd 형식을 확인해주세요.'
- 로그인 실패 -> '로그인 중 오류가 발생했습니다. 다시 시도해주세요.'
<br/>
<br/>
- Issue: #
> ✨feat:로그인실패시 오류메시지

- src/components/interest-heart/interestCss.ts
- src/pages/aidrq-detail-page/index.tsx
- src/pages/aidrq-detail-page/indexCss.ts
- src/store/queries/aidreq-detail-volunteer-query/usePresentStatus.ts
- src/store/queries/aidreq-detail-volunteer-query/useWithdrawAidRq.ts
- presentState?.status === 'WAITING' || presentState?.status === 'APPROVED' 일 때 "철회하기" 버튼으로 바뀌고, 그 외의 경우에는 "지원하기" 버튼이 뜨도록 조건문 달았습니다.
- 비활성화 처리 로직에 위 조건문 추가해서 "철회하기" 버튼이 활성화 되도록 변경하였습니다.
- max-width: 1000px일 때 관심기관 등록 버튼에 right: 0 추가했습니다.
- 지원/리뷰 버튼 BOX width: 440px로 수정하였습니다.
<br/>
<br/>
- Issue: #449
> Feawt/#449/모집글철회 버튼수정

- src/components/aidrq-create-date/indexCss.ts
- src/features/aidrq-create-shared-part/ui/select-container/indexCss.ts
- src/pages/aidrq-create-page/indexCss.ts
- src/pages/aidrq-create-page/ui/recruit-population/indexCss.ts
- src/pages/aidrq-create-page/ui/volunteer-date/indexCss.ts
- src/pages/aidrq-create-page/ui/volunteer-hour/indexCss.ts
- src/shared/hooks/usePostCode.ts
- 모집글 장소설정 오류 날 시, 에러메시지 출력
- 모집글 페이지 반응형 완료
<br/>
<br/>
- Issue: #
> ✨feat:모집글등록 추가기능구현

- src/pages/aidrq-modify-page/indexCss.ts
- src/pages/aidrq-modify-page/ui/info-modify/indexCss.ts
- src/pages/aidrq-modify-page/ui/location-modify/indexCss.ts
- 수정하기 페이지 반응형 완료
<br/>
<br/>
- Issue: #
> ✨feat:수정페이지반응형

- src/features/aidrq-list-main-page/indexCss.ts
- src/features/main-banner/indexCss.ts
- src/pages/main-page/MainpageCss.ts
- src/pages/main-page/_components/aidrq-recent-list/indexCss.ts
- src/pages/main-page/_components/community/indexCss.ts
- 메인페이지 반응형 1차 완료
<br/>
<br/>
- 봉사왕 부분은 제외하고 하였음. (아예 안건드림 - 봉사왕 퍼블 PR이랑 컨플릭트 가능성)
- Issue: #
> ✨feat:메인페이지 반응형

- src/layout/Layout.tsx
- src/layout/LayoutCss.ts
- src/layout/header/Header.tsx
- src/store/queries/logout-query/useCommonLogout.ts
- src/store/queries/logout-query/useVolunteerLogout.ts
- src/store/stores/login/loginStore.ts
- 로그아웃 통합 및 session에서 token제외시키기
- footer 항상 뷰포인트보다 밑에 있게, 항상 최하단에 위치하도록
<br/>
<br/>
- Issue: #
> 🐛fix:logout및footer수정

- src/pages/login-page/LoginPage.tsx
- src/pages/login-page/logic/useSocialLogin.ts
- 소셜로그인 시, post요청을 보내는 것으로 테스트
<br/>
<br/>
- Issue: #
> ✨feat:배포사이트 소셜로그인 테스트

- src/pages/login-page/logic/useSocialLogin.ts
- src/pages/main-page/MainPage.tsx
- jwt토큰 해석해서 zustand에 user-info저장
- user-info api 필요없어짐
- 소셜로그인 테스트했던 것 다시 원상복구 (post요청에서 window.location.href로 재변경)
<br/>
<br/>
- Issue: #
> ✨feat:jwt디코딩 및 소셜로그인로직 복구

- src/pages/aidrq-modify-page/ui/info-modify/index.tsx
- src/pages/aidrq-modify-page/ui/location-modify/index.tsx
- 활동 시작일 00시 00분 부터는 수정하기 버튼을 눌러도 '봉사 시작일 이후에는 정보를 수정할 수 없습니다.' 라는 문구가 뜨도록 설정
<br/>
<br/>
- Issue: #
> ✨feat:수정제출가능여부 판별로직

- src/features/message-create-modal/index.tsx
- src/features/message-create-modal/indexCss.tsx
- src/features/message-create-modal/logic/useSendMail.ts
- src/store/queries/message-create-common-query/usePostMessage.ts
- 쪽지작성 모달 css 깨지는 부분 수정 / 반응형
- 쪽지 전송 실패시 해당 메시지 띄우도록 수정
<br/>
<br/>
- Issue: #478
> 478 feature 쪽지작성모달 css

- src/components/applicant-list-item/indexCss.ts
- src/features/applicant-list/indexCss.ts
- src/pages/aidrq-applicant-list-page/index.tsx
- src/pages/aidrq-applicant-list-page/indexCss.ts
- src/pages/aidrq-applicant-list-page/ui/title/indexCss.ts
- 지원자 현황 페이지 반응형 작업
<br/>
<br/>
- 지원자 상세 프로필 조회 모달 반응형
- Issue: #459
> ✨ [#459] Feat: 지원자 현황 페이지 반응형

- src/features/applicant-detail-modal/indexCss.ts
> 🚑️ [#474] Feat: 지원자 현황 페이지의 지원자 상세 프로필 조회 반응형 완료

- package.json
- public/assets/imgs/plus.svg
- public/assets/imgs/slash.svg
- src/features/personal-my-page-title-with-pagenation/index.tsx
- src/features/personal-my-page-title-with-pagenation/indexCss.ts
- yarn.lock
- 개인 마이페이지에 아이콘 추가해서 적용했습니당
<br/>
<br/>
- Issue: #477
> 💄 Style: 개인마이페이지 아이콘 추가

- src/features/personal-my-page-review-list/_component/ReviewBox.tsx
- src/features/personal-my-page-review-list/_component/ReviewBoxCss.ts
- src/features/personal-my-page-review-list/index.tsx
- src/features/personal-my-page-review-list/logic/useMyReview.ts
- src/features/review-read-modal/index.tsx
- src/features/review-read-modal/logic/useFindReview.tsx
- src/store/queries/center-profile-query/useFetchCenterData.ts
- src/store/queries/volunteer-profile/useFetchPersonProfile.ts
- 개인마이페이지 리뷰모달 띄우도록 수정했습니다.
- 프로필을 기관으로 띄우기 위해서는 기관 id가 필요할 것 같아서 백엔드와 논의할 예정
- 리뷰를 불러오지 못했다면 alert 띄우도록 처리
<br/>
<br/>
- Issue: #415
> ✨ Feat: 개인마이페이지 리뷰모달 추가(프로필 기관으로 변경 필요)

- src/components/select/index.tsx
- src/components/select/indexCss.ts
- src/components/tab-button/ui/index.tsx
- src/components/tab-button/ui/indexCss.ts
- src/features/center-profile-prefer-item-box/index.tsx
- src/pages/aidrq-detail-page/index.tsx
- props camelCase오류 디버깅 (tabbutton filterbox 등)
- console지우기
- 지원상태 불러오는 api 호출로직에 Role이 volunteer일 때에만 호출하도록 수정
<br/>
<br/>
- Issue: #
> 🐛fix:console및props오류개선

- src/features/aidrq-list-admin/indexCss.ts
- src/pages/aidrq-create-page/ui/explanation/index.tsx
- src/pages/aidrq-create-page/ui/explanation/indexCss.ts
- src/pages/aidrq-modify-page/ui/info-modify/index.tsx
- src/pages/aidrq-modify-page/ui/info-modify/indexCss.ts
- 봉사활동모집글에 텍스트에디터 추가
- 기관마이페이지 admin list page에 width조정
(section 자체가 90%라서 그 내부 feature에서는 90%->100%로 변경)
<br/>
<br/>
- Issue: #
> ✨feat:봉사활동모집글에 텍스트에디터 추가

- src/features/review-create-modal/index.tsx
- src/features/review-create-modal/indexCss.ts
- src/pages/aidrq-detail-page/index.tsx
- 리뷰 작성 시 alert창 띄우기
- 리뷰 상세설명부분 텍스트에디터로 변경하기
- 리뷰 작성 여부에 따라 리뷰버튼에 '이미 작성한 리뷰가 있습니다.' 문구 띄우기
<br/>
<br/>
- Issue: #
> ✨feat: review모달 기능추가 및 수정

- src/features/personal-my-page-half-list/logic/useHalfList.ts
- src/features/personal-my-page-interest-center-list/index.tsx
- src/features/personal-my-page-interest-center-list/indexCss.ts
- src/features/personal-my-page-interest-center-list/logic/useMyInterestCenter.ts
- src/pages/personal-my-page/_component/logic/useMyProfileData.ts
- 처음 페이지 접속시에 ref 적용한 요소의 width를 제대로 못가져오는 오류
- useEffect -> useLayoutEffect 사용
<br/>
- 큰화면
- 작은화면
<br/>
- Issue: #483
> 483 fix 개인마이페이지 관심기관 리스트 반응형 문제

- src/features/adjustment-modal/index.tsx
- src/features/adjustment-modal/indexCss.ts
> 🚑️ [#461] Feat: 정산하기 모달 반응형 완료

- src/pages/aidrq-detail-admin-page/index.tsx
- src/pages/aidrq-detail-admin-page/ui/button-group/index.tsx
- 기관 모집글 관리페이지에서 수정하기버튼 비활성화 로직
- 봉사시작일 이전에만 활성화
<br/>
<br/>
- Issue: #
> ✨feat:수정하기버튼 비활성화 스케쥴링

- src/pages/login-page/logic/useLogin.ts
- src/pages/main-page/MainPage.tsx
- 로고 클릭 시, 로그아웃되는 이슈
- mainpage) token을 loginpage에서 state로 받던 것을 session에서 새로 가져오는 것으로 변경
<br/>
<br/>
- Issue: #
> 🐛fix:mainpage토큰판별방식 수정

- src/features/communitiy-detail-comment-box/logic/useCommunityComment.ts
- 댓글 글자수제한
<br/>
<br/>
- 로그인 회원가입 완료된 뒤 테스트하기
- Issue: #
> ✨feat:댓글 글자수제한

- src/pages/main-page/MainPage.tsx
- 로그인 info 변경 (id -> roleId)
<br/>
<br/>
- Issue: #
> 🐛fix:로그인info변경

- src/features/edit-center-profile/_components/profile-edit-form/index.tsx
- src/features/personal-my-page-edit-profile/logic/useEditMyProfile.ts
> ✨ [#511] Feat: 기관/봉사자 마이페이지 글자수 제한

- src/pages/login-page/logic/useLogin.ts
- src/pages/signup-page/index.tsx
- src/store/queries/signup-query/duplicateCheck.ts
- src/store/queries/signup-query/useSignUp.ts
- 회원가입 로직 개발 완료
- 회원가입 유효성 -> 아이디 중복검사 및 비밀번호 일치
- 회원가입 완료 시, OpenAlert와 함께 login페이지로 이동
<br/>
<br/>
- 소셜로그인 / 상세입력페이지
- Issue: #
> ✨feat:회원가입로직완료

- src/features/find-nearby-activity-search/index.tsx
- src/features/find-nearby-activity-search/indexCss.ts
- src/pages/find-nearby-activitiy-page/index.tsx
- 주변 검색했을 때 데이터가 없을 경우 데이터 없음 표시
<br/>
- Issue: #517
> ♻️ [#517] Refactor: activieis.length === 0 일 때 noData 표시

- src/pages/main-page/_components/ranking/index.tsx
- src/pages/main-page/_components/ranking/indexCss.ts
- src/pages/main-page/_components/ranking/ui/rank-item/index.tsx
- src/pages/main-page/_components/ranking/ui/rank-item/indexCss.ts
- src/shared/types/ranking-data/RankingDataType.ts
- 드롭다운 퍼블리싱했습니다!
- 추후 api 나오면 수정후 머지할 예정입니다
<br/>
<br/>
- Issue: #362 
- z-index가 적용안되는 이슈때문에 조금 오래걸렸습니다
> 362 feature main 봉사왕 수정사항 퍼블리싱

- src/components/tab-button/indexCss.ts
- src/main.tsx
- src/mocks/handlers/index.tsx
- src/mocks/handlers/ranking.mock.ts
- src/pages/main-page/_components/ranking/index.tsx
- src/pages/main-page/_components/ranking/indexCss.ts
- src/pages/main-page/_components/ranking/ui/rank-item/index.tsx
- src/pages/main-page/_components/ranking/ui/rank-item/indexCss.ts
- src/shared/types/ranking-data/RankingDataType.ts
- src/store/queries/main-page-common-query/useFetchRanking.ts
- 봉사랭킹 기능구현
- 로직구현(현재는 DB에 데이터가 없어서 msw연결 -> msw 연결만 끊으면 됨)
- 랭킹이 같은 경우에는 '닉네임 외 ㅁ명' 식으로 표현 -> 호버 시 드롭다운, 클릭 시 프로필로 이동
- 반응형구현
<br/>
<br/>
- Issue: #
> ✨feat:봉사랭킹 기능구현

- src/components/inputBox/indexCss.ts
- src/pages/signup-page/index.tsx
- 중복확인에 성공할 경우, 아이디 입력input창이 disable처리됨 (fix됨)
<br/>
<br/>
- Issue: #
> 🐛fix:중복확인시, input disable처리

- src/shared/hooks/useCenterInfiniteAidRq.ts
- src/shared/hooks/useInfiniteAidRq.ts
- 기관 모집글 조회 엔드포인트 centerId -> me로 변경
- 메인페이지에 보여지는 "/aidrqlist" 경로의 api axios -> axiosInstance로 변경하며 response 구조 변경
- 백엔드에서 기관이 작성한 모집글 리스트 엔드포인트 me로 바꿔주면 확인 테스트 필요합니다.
- 테스트 후 axios -> axiosInstance로 바꾸겠습니다.
- Issue: #529
> ♻️ [#529] Refactor: 기관 모집글 조회 엔드포인트 변경, 메인페이지 모집글 axiosInstance로 변경

- src/features/alert/indexCss.ts
- 알림창 높이고정 및 스크롤구현
<br/>
<br/>
- Issue: #
> ✨feat:알림창 높이고정 및 스크롤구현

- src/pages/aidrq-detail-page/index.tsx
- src/store/queries/aidreq-detail-volunteer-query/usePresentStatus.ts
- 지원현황 api 수정 및 axiosInstance로 변경
<br/>
<br/>
- Issue: #
> ✨feat:지원현황조회api수정

- src/api/routes/index.tsx
- src/pages/login-page/logic/useLogin.ts
- src/pages/main-page/MainPage.tsx
- src/pages/success-page/index.tsx
- 로그인 후 이동할 sucess페이지 제작 (여기서 로그인 관련 로직 및 판별 모두 일괄처리 후 메인or상세정보입력페이지로 리디렉션)
<br/>
<br/>
- Issue: #
> ✨feat:success페이지 개발

- src/store/queries/signup-query/duplicateCheck.ts
- 중복확인 api 변경사항 수정
<br/>
<br/>
- Issue: #
> 🐛fix:중복확인api수정

- src/pages/detail-info-page/volunteer/index.tsx
- src/components/applicant-list-item/index.tsx에 email 필드가 있는데 아직 머지 안된 것 같아서 되면 수정 하겠습니다.
- 봉사자 상세 정보 입력 페이지의 이름 input label에 "기관명"으로 되어 있어 "이름"으로 label 변경하였습니다.
<br/>
<br/>
- Issue: #545
> 🐛 [#545] Fix: 봉사자 상세정보 입력 폼 기관명 -> 이름으로 변경

- src/features/aidreq-detail-center-profile/_components/info-container/index.tsx
- src/features/profile-page-img-box/index.tsx
- homepage_link -> homepage_url로 변경
<br/>
- Issue: #562
> 🐛 [#562] Fix: homepage_link -> homepage_url로 변경

- src/components/route/ProtectedRoute.tsx
- src/main.tsx
- src/pages/main-page/_components/ranking/index.tsx
- src/store/queries/main-page-common-query/useFetchMainCommunity.ts
- src/store/queries/main-page-common-query/useListShort.ts
- 가끔 전체기능이 마비되는 오류를 디버깅하기 위한 1차 테스트
- 랭킹부분 공석처리 및 msw끄기
<br/>
<br/>
- Issue: #
> 🐛fix: ProtectedRoute디버깅테스트 및 랭킹디버깅

- src/components/applicant-list-item/index.tsx
- src/features/personal-my-page-edit-profile/index.tsx
- src/features/personal-my-page-edit-profile/logic/useEditMyProfile.ts
- src/pages/personal-my-page/_component/PMPGTop.tsx
- src/shared/types/person-profile/personProfile.ts
- src/store/queries/aidreq-detail-admin-query/useApplicantDetail.ts
- src/store/queries/center-mypage/useCenterProfile.ts
- src/store/queries/volunteer-mypage/usePutMyProfile.ts
- src/store/queries/volunteer-profile/useFetchPersonProfile.ts
- 봉사자 마이페이지의 프로필 수정 api 변경
- 기관이 조회하는 봉사자 상세 프로필 조회 api 변경
- 봉사자가 조회하는 타인 프로필 조회 api 변경
- 필요없는 주석 제거
<br/>
<br/>
- 이미지 수정 연결
- Issue: #561
> ♻️ [#561] Refactor: 봉사자 프로필 조회 api 변경

- src/features/personal-my-page-edit-profile/logic/useEditMyProfile.ts
> img 상태변수 임시 제거

- src/pages/detail-info-page/volunteer/index.tsx
- src/pages/detail-info-page/volunteer/indexCss.ts
- 상세정보 입력 시, 유효성검사 (전화번호)
<br/>
<br/>
- Issue: #
> ✨feat: 상세정보입력 유효성검사

- src/features/applicant-detail-modal/index.tsx
- src/features/edit-center-profile/_components/profile-edit-form/index.tsx
- src/features/edit-center-profile/index.tsx
- src/features/edit-center-profile/logic/useEditCenterProfile.ts
- 지원자 상세 프로필 생년월일 제거
- 기관 마이페이지 URL 검증 제거
- 사이트 주소 빈 문자열로 수정하기 시도할 경우 에러 메세지 "사이트 주소를 입력해주세요."로 변경
- 각 입력폼 빈값일 경우, 유효성 검사 만족 못하는 경우 조건문 추가하여 상황에 맞는 경고창 띄우도록 수정
<br/>
<br/>
- Issue: #572
> Refactor/#572/생년월일 사이트유효성 제거

- src/api/apis/index.tsx
- src/components/route/ProtectedRoute.tsx
- src/layout/header/Header.tsx
- src/pages/login-page/logic/useLogin.ts
- src/pages/main-page/MainPage.tsx
- src/pages/success-page/index.tsx
- src/store/stores/login/loginStore.ts
- token localStorage에 저장
<br/>
<br/>
- Issue: #
> ✨feat:token을 localStorage에서 관리

- src/api/apis/index.tsx
- src/pages/success-page/index.tsx
- src/store/queries/update-login-info/updateLoginInfo.ts
- token 기간 만료 후 리프레시 로직 테스트 1차
<br/>
<br/>
- 로그인 로직 변경 후, 추가 확인 예정
- Issue: #
> ✨feat:토큰리프레시 테스트 1차

- src/pages/login-page/logic/useLogin.ts
- src/pages/login-page/logic/useSocialLogin.ts
- src/pages/main-page/MainPage.tsx
- src/pages/success-page/index.tsx
- 단기토큰으로 ACCESS받아오기 테스트 1차
<br/>
<br/>
- Issue: #
> ✨feat:로그인 단기토큰 이용 로직

- src/pages/success-page/index.tsx
- 테스트를 위한 배포서버에 콘솔 및 오류디버깅 테스트코드 업데이트
<br/>
<br/>
- Issue: #
> 🐛fix:로그인로직 디버깅 1차

- src/features/aidreq-detail-center-profile/_components/info-container/index.tsx
- src/features/profile-page-img-box/index.tsx
- src/features/profile-page-info-box/index.tsx
- src/pages/main-page/MainPage.tsx
- src/shared/types/center-profile/centerProfile.ts
- 기관 프로필 조회에서 center_id가 id로 변경됨에 따라 관심기관 로직에 데이터 파싱 수정
<br/>
<br/>
- Issue: #
> 🐛fix:관심기관프로필조회 type: center_id->id로변경

- src/components/inputBox/index.tsx
- src/features/communitiy-detail-comment-box/index.tsx
- src/features/communitiy-detail-content-box/index.tsx
- src/features/communitiy-detail-content-box/logic/useCommunityDetailContent.ts
- src/features/community-list/index.tsx
- src/features/personal-my-page-half-list/index.tsx
- src/pages/main-page/_components/community/indexCss.ts
- 커뮤니티 작성자 프로필 확인가능 / 기관은 작성 및 댓글 불가
<br/>
<br/>
- Issue: #
> 🐛fix:커뮤니티 작성자 프로필 확인가능 / 기관은 작성 및 댓글 불가

- src/features/community-create-box/logic/useCreateCommunity.ts
- src/features/message-read-modal/index.tsx
- src/features/personal-my-page-half-list/index.tsx
- src/store/queries/center-mypage/useMessage.ts
- src/store/queries/community-create-common-query/useControlCommunity.ts
- 커뮤니티 수정/작성 json으로 변경
- 봉사자 마이페이지 쪽지 조회 모달 열 때 type='volunteer' props 추가
<br/>
<br/>
- Issue: #595
> Fix/@595/기관 쪽지 티어 에러

- src/features/adjustment-modal/index.tsx
- 정산 alert -> useAlertDialog의 openAlert로 변경
- Issue: #591
> 💄 [#591] Style: 정산 alert -> useAlertDialog의 openAlert로 변경

- src/features/edit-center-profile/index.tsx
- src/features/edit-center-profile/logic/useEditCenterProfile.ts
- src/store/queries/center-mypage/useCenterProfile.ts
- 이미지 수정 api로 put 요청을 보내 pre-signed url 반환 받는 것까지는 확인했습니다. 
- 그런데 local로 url 요청 다시 보내니 cors 에러 나는 것 같아서 업데이트 되면 테스트 해봐야 할 것 같습니다. 
- 배포에서 테스트 잘 되면 봉사자 마이페이지에도 적용하겠습니다. 
- Issue: #600
> ♻️ [#600] Refactor: 기관 마이페이지  프리사인드 이미지 업로드 적용

- src/features/personal-my-page-edit-profile/logic/useEditMyProfile.ts
- src/store/queries/center-mypage/useCenterProfile.ts
- 특수 문자 앞에 replace 함수로 \(이스케이프) 수동으로 추가 후 url put 요
<br/>
<br/>
- Issue: #605
> ♻️ Refactor: pre-signed url의 &, = 앞에 이스케이프 문자 추가
